arm:
  # kinematics_solver: phantomx_pincher_arm/IKFastKinematicsPlugin
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  # position_only_ik: True
